default_env: &default
  adapter: postgresql
  encoding: unicode
  database: muscle_top
  url: <%= ENV["DATABASE_URL"] %>
development:
  <<: *default

production:
  <<: *default
  # url: <%= ENV["DATABASE_URL"] %>